name: Flutter CI/CD Android

on:
  push:
    branches:
      - release
      - dev
  pull_request:
    branches:
      - release
      - dev

jobs:
  build:
    name: Build & Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > android/app/google-services.json

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Set build name and number
        run: |
          echo "BUILD_NAME=${{ github.run_number }}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ secrets.BUILD_NUMBER }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --build-number=${{ env.BUILD_NUMBER }}  --build-name=${{ env.BUILD_NAME }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers-group
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Test release 🚀"
